# Generated by Django 4.1.1 on 2022-11-02 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0014_usercategory_category_category_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategory',
            new_name='UserCategorySub',
        ),
    ]
