# Generated by Django 4.1.1 on 2022-11-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_usercategory_usercategorysub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_user',
        ),
    ]
