# Generated by Django 4.1.1 on 2022-11-02 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0016_remove_category_category_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategorySub',
            new_name='UserCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='category_user',
            field=models.ManyToManyField(through='news.UserCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
