# Generated by Django 4.1.1 on 2022-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_all',
            new_name='comment_all_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='post_author_id',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='post_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
