# Generated by Django 4.1.1 on 2022-09-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_author_author_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_author_id',
            new_name='post_author',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post_id',
            new_name='post',
        ),
    ]
