# Generated by Django 4.1.1 on 2022-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_time_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
