# Generated by Django 4.1.1 on 2022-11-02 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_category_category_user_alter_usercategory_user_and_more'),
    ]

    operations = [

    ]
