# Generated by Django 4.1.1 on 2022-11-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_category_category_user_delete_usercategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_user',
            new_name='user_category',
        ),
    ]
