# Generated by Django 4.1.1 on 2022-09-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_author_id_author_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_all_id',
            new_name='comment_all',
        ),
    ]
