# Generated by Django 4.1.1 on 2022-09-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_comment_all_id_comment_comment_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating_author',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_to_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_all',
            new_name='comment_who',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating_comment',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_add_comment',
            new_name='time_add',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating_post',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_post',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time_add_post',
            new_name='time_add',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_post',
            new_name='title',
        ),
    ]
